version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: pino-pretty
    versions:
    - 4.4.0
    - 4.5.0
    - 4.6.0
    - 4.7.0
    - 4.7.1
  - dependency-name: ini
    versions:
    - 1.3.7
